### PR TITLE
Markdown cleanup. Some typos fixed.

### PR DESCRIPTION
**Pull request by matt-the-ogre**
There was a typo in the "Pre-mortem" student guide.

Cleaned up Markdown to be consistent with accepted style guides.

Changed codeblocks ("```") for sample prompts to quotes (">") as a suggestion.

### CODE REVIEW

**Comment by matt-the-ogre** [comment]
@microsoft-github-policy-service agree

**Comment by cricex** [comment]
Hi @matt-the-ogre, I agree that quotes displays better than code blocks. We decided to go with code blocks because the built-in copy to clipboard functionality. It doesn't appear to be there for quotes.

Example:
image

**Comment by matt-the-ogre** [comment]
Oh that's makes a lot of sense. Want me to revert those bugs keep the other changes in my PR?

**Comment by cricex** [comment]
> Oh that's makes a lot of sense. Want me to revert those bugs keep the other changes in my PR?

Hi @matt-the-ogre , sorry for the delay on this one! Yes, go ahead and revert the bugs & keep other changes to the PR.

**Comment by matt-the-ogre** [comment]
I'm going to close this and re-open another one.

**Pull request closed without merging**
